export const GET_PATIENTS = "GET_PATIENTS";
export const SELECT_PATIENT = "SELECT_PATIENT";
export const REQUEST_PATIENTS = "REQUEST_PATIENTS";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS"

export const GET_WOUNDS = "GET_WOUNDS";
export const SELECT_WOUND = "SELECT_WOUND";
export const REQUEST_WOUNDS = "REQUEST_WOUNDS";
export const RESOLVE_WOUND = "RESOLVE_WOUND";